pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
     stage('Checkout Code') {
       steps {
              checkout scm
             }
        }
    stage('build') {
      steps {
        sh 'node app.js'
      }
    }
  }
}
