pipeline {
    agent {
        docker {
            image 'python:3.10-slim'
            label 'docker'
        }
    }
    stages {
        stage('Run Hello World') {
            steps {
                echo 'Starting Hello World Python script...'
                sh 'python3 app/hello.py'
            }
        }
    }
    post {
        always {
            echo 'Pipeline complete.'
        }
    }
}
