pipeline {
    agent {
        docker {
            image 'python:3.10-slim'
        }
    }
    stages {
        stage('Run Hello World') {
            steps {
                echo 'Starting Hello World Python script...'
                sh 'python3 My-test-code/app/hello.py'
            }
        }
        stage('Debug - List Files') {
            steps {
                sh 'ls -R'
            }
        }
    }
    post {
        always {
            echo 'Pipeline complete.'
        }
    }
}
